# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    admin.workspace:
        class: AppBundle\Admin\WorkspaceAdmin
        arguments: [~, AppBundle\Entity\Workspace, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Workspace }

    admin.project:
        class: AppBundle\Admin\ProjectAdmin
        arguments: [~, AppBundle\Entity\Project, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Project }

